### PR TITLE
fix(extension-chrome): enable for http and local site 

### LINKED ISSUE #172: [enable_wallet] failed
nexus version : https://github.com/ckb-js/nexus/commit/f9f18a74bb3c60baddc3fab04590eaddd1498990
url: http://192.168.31.66:3000/
image

url: http://info.cern.ch/
image

### PR DESCRIPTION
**Pull request by homura**
## What Changes

Resolve #172 

## Change Type

Indicate the type of change your pull request is:

- [ ] `documentation`
- [x] `patch`
- [ ] `minor`
- [ ] `major`

:baby_chick: Download canary assets:

[nexus--canary.174.4555510584.zip](https://github.com/ckb-js/nexus/releases/download/v0.0.0-canary/nexus--canary.174.4555510584.zip)

### CODE REVIEW

File: packages/extension-chrome/src/contentScript/inpage.ts [hunk 1]
```diff
@@ -1,14 +1,15 @@
...
 import { EventEmitter } from 'eventemitter3';
 import { isEventObject } from '../messaging/internal';
 import { createInjectedCkb } from '../injectedCkb';
-import { RpcClient, RpcMethods } from '@nexus-wallet/types';
+import type { RpcClient, RpcMethods } from '@nexus-wallet/types';
 
 const client = new JSONRPCClient(async (req) => {
   const response = await windowMessenger.sendMessage('contentAndInjected', req, 'content-script');
-  asserts.asserts(isJSONRPCResponse(response), `Invalid JSON-RPC response: ${response}`);
+  if (!isJSONRPCResponse(response)) {
```
Comment (zhangyouxin) [inline packages/extension-chrome/src/contentScript/inpage.ts:10]: Looks like an unnecessary change

File: packages/extension-chrome/__tests__/utils/validate.test.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+  });
+
+  it('should be invalid', () => {
+    expect(() => validateHost('')).toThrowError();
+    expect(() => validateHost(' ')).toThrowError();
+    expect(() => validateHost('localhost:')).toThrowError();
+    expect(() => validateHost('localhost: ')).toThrowError();
+    expect(() => validateHost('localhost: 1234')).toThrowError();
+    expect(() => validateHost('localhost:1234 ')).toThrowError();
+    // IP could not larger than 255
```
Comment (zhangyouxin) [inline packages/extension-chrome/__tests__/utils/validate.test.ts:22]: maybe we should only allow [private network addresses](https://en.wikipedia.org/wiki/Private_network) when an IP address is detected:

- 192.168.0.0/16 
- 172.16.0.0/12 
- 10.0.0.0/8

Because the motivation of allowing ip addresses is only for DApp development when testing locally, real DApp production should not use a domain rather than IP address.

**Review by gpBlockchain — APPROVED** [review]

File: packages/extension-chrome/__tests__/utils/validate.test.ts (hunk 2 above)
Comment (homura) [reply packages/extension-chrome/__tests__/utils/validate.test.ts:22]: If we disable the use of IP access, it will make the development inconvenient. Imagine we are working together, the contract engineer has developed the contract, the front-end engineer has developed the relevant pages, when they want to debug, they will generally use the private network for debugging, which is often the fastest way to use the private network IP address to debug

If a fishing dApp publishes a site using IP without using domain name, it may be a bit choking if we forbid IP access for such a rare case, at this stage we may consider how to make it convenient for developers, at a later stage, we may be able to make these functions into advanced configuration

**Review by zhangyouxin — APPROVED** [review]
