### PR TITLE
fix(ownership-providers): inject witness and cellDeps auto

### LINKED ISSUE #248: Making `FullOwnership` more convenient
> when I started working on this issue to add a transfer example, I found that the `FullOwnership` is not quite convenient, since
> 
> - it doesn't inject the `cellDeps` automatically when `injectCapacity`
> - it doesn't inject the corresponding witness when `injectCapacity`
> - it doesn't filter out the same input when `injectCapacity`

_Originally posted by @homura in https://github.com/ckb-js/nexus/issues/220#issuecomment-1515649417_

### PR DESCRIPTION
**Pull request by homura**
# What Changed

Resolve #248 

## Change Type

Indicate the type of change your pull request is:

- [ ] `documentation`
- [x] `patch`
- [ ] `minor`
- [ ] `major`

:baby_chick: Download canary assets:

[nexus--canary.251.4787742070.zip](https://github.com/ckb-js/nexus/releases/download/v0.0.0-canary/nexus--canary.251.4787742070.zip)

<details>
  <summary>📦 Published PR as canary version: <code>0.0.16--canary.251.4787742070.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @nexus-wallet/ownership-providers@0.0.16--canary.251.4787742070.0
  npm install @nexus-wallet/protocol@0.0.16--canary.251.4787742070.0
  npm install @nexus-wallet/utils@0.0.16--canary.251.4787742070.0
  # or 
  yarn add @nexus-wallet/ownership-providers@0.0.16--canary.251.4787742070.0
  yarn add @nexus-wallet/protocol@0.0.16--canary.251.4787742070.0
  yarn add @nexus-wallet/utils@0.0.16--canary.251.4787742070.0
  ```
</details>

### CODE REVIEW

File: packages/ownership-providers/src/FullOwnershipProvider.ts [hunk 1]
```diff
@@ -329,6 +358,19 @@ export class FullOwnershipProvider {
...
+  // TODO: wait for wallet provider a API to get genesis block
+  private async getSecp256k1Blake160Config(): Promise<ScriptConfig> {
+    const config = await this.getLumosConfig();
+    const result = config.SCRIPTS.SECP256K1_BLAKE160;
+    assert(result, 'Cannot find secp256k1_blake160 config in lumos config');
+    return result;
+  }
+
   // TODO: wait for wallet provide a API to get genesis block hash
   private async getLumosConfig(): Promise<LumosConfig> {
```
Comment (zhangyouxin) [inline packages/ownership-providers/src/FullOwnershipProvider.ts:375]: we can remove this method if we nerver use it.

File: packages/ownership-providers/src/FullOwnershipProvider.ts [hunk 2]
```diff
@@ -159,17 +173,32 @@ export class FullOwnershipProvider {
...
 
+    const cellDep = await this.getSecp256k1Blake160CellDep();
+
     txSkeleton = txSkeleton
       .update('inputs', (inputs) => {
-        return inputs.push(...inputCells);
+        return inputs.push(...injectedCells);
+      })
+      .update('witnesses', (witnesses) => {
+        const inputWitnesses = injectedCells.map(() => SECP256K1_BLAKE160_WITNESS_PLACEHOLDER);
```
Comment (zhangyouxin) [inline packages/ownership-providers/src/FullOwnershipProvider.ts:188]: This logic makes `injectCapacity` only allowed to be called once on a txSkeleton, because if you call `injectCapacity` the second time, there will be too many witnesses.
we should check the length of `inputs` and existing `witnesses`.

File: packages/ownership-providers/src/FullOwnershipProvider.ts (hunk 1 above)
Comment (homura) [reply packages/ownership-providers/src/FullOwnershipProvider.ts:375]: It is [in use](https://github.com/ckb-js/nexus/pull/251/files#diff-4212a8e65e25ac3827c0789664613414267d82d12237316f5b3adf09ac533476R368), but we'll refactor it

File: packages/ownership-providers/src/FullOwnershipProvider.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (homura) [reply packages/ownership-providers/src/FullOwnershipProvider.ts:188]: yup, we should skip injecting witnesses if they are the same lock group, can you help me to create a patch to implement it?

**Comment by zhangyouxin** [comment]
https://github.com/ckb-js/nexus/pull/251/files#diff-4212a8e65e25ac3827c0789664613414267d82d12237316f5b3adf09ac533476R392-R399 This private method is not in use any more, I'll remove it btw.

**Review by IronLu233 — APPROVED** [review]

**Comment by homura** [comment]
> [#251 (files)](https://github.com/ckb-js/nexus/pull/251/files#diff-4212a8e65e25ac3827c0789664613414267d82d12237316f5b3adf09ac533476R392-R399) This private method is not in use any more, I'll remove it btw.

removed in [40501cb](https://github.com/ckb-js/nexus/pull/251/commits/40501cb7aad4abf983e7572f3f18ec72326179bc)

**Review by zhangyouxin — APPROVED** [review]
